# Generated by Django 5.0.3 on 2024-03-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Вставьте файл с картинкой'),
        ),
        migrations.AddField(
            model_name='book',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='nusic/', verbose_name='Вставьте музыку '),
        ),
        migrations.AddField(
            model_name='book',
            name='type_books',
            field=models.CharField(choices=[('Художественная литература', 'Художественная литература'), ('Детективы', 'Детективы'), ('Любовные романы', 'Любовные романы'), ('Приключения', 'Приключения'), ('Манга', 'Манга')], max_length=100, null=True, verbose_name='Выберите жанр книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Вставьте url ссылку YouTube ролика'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True, verbose_name='Напишите описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=1000000, null=True, verbose_name='Задайте цену'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Напишите название книги'),
        ),
    ]
