# Generated by Django 5.0.3 on 2024-03-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_options_book_image_book_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='autor',
            field=models.CharField(max_length=100, null=True, verbose_name='Напишите имя автора'),
        ),
        migrations.AddField(
            model_name='book',
            name='full_description',
            field=models.TextField(null=True, verbose_name='Напишите полное описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True, verbose_name='Напишите краткое описание книги'),
        ),
    ]
